# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: Dal Biosignal Lab

# Below the site title
tagline: "Human neurophysiology imaging: Developing software and hardware tools to understand the brain."

# Site logo - replaces the site title above
logo: dal_logo_tra.png

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  BlogBox is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net.

# The base hostname & protocol of your site for where absolute urls are needed
url: https://tbardouille.github.io

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
#- text: Style Guide
#  url: /style-guide/
- text: Archives
  url: /tags/

# Author information - author info at the bottom of the post
author_name: "Tim Bardouille"
author_bio: "I’m an Associate Professor at Dalhousie University who’s been 
  non-invasively imaging human neurophysiology since Y2K. I'm affiliated with the 
  Physics, 
  Medical Physics, 
  Biomedical Engineering, and 
  Psychology and Neuroscience 
  departments at Dal."
author_url: "https://www.dal.ca/faculty/science/physics/faculty-staff/Faculty/TimBardouille.html"
author_location: "Halifax, NS, Canada"
author_image: TimBardouille_Proof1.jpg

# Footer ad banner
banner_image: 
banner_url: 

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: 

# Social links in the site footer
twitter_username: 
facebook_username: 
github_username: tbardouille
codepen_username: 
dribbble_username: 
medium_username: 
instagram_username: 
pinterest_username: 
linkedin_username: tim-bardouille

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
